### ISSUE TITLE
Set up docker deploy/push actions

### ISSUE THREAD

**Issue by wasabi222** [wasabi222/janitor#29]
I'm attempting to set up auto pushing of docker images on merge. This requires setting up my docker hub user/pass as a secret, so I need to remove @mirceaulinic @zachmoody and @alext as collaborators first

**Comment by mirceaulinic** [comment]
No problems at all from my side, haven't actually contributed anything useful for a long time - but I think you can setup Docker hub without adding the secrets in GH (I don't recall having to add any where I have automatic builds).
